/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controllers.ReservaController;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Reserva;

/**
 *
 * @author Guilherme Luvison
 */
public class ListarReservas extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListarReservas.class.getName());
    private final ReservaController rc = new ReservaController();
    private DefaultTableModel modeloTabela;
    private final JFrame telaInicial;

    /**
     * Creates new form ListarReservas
     */
    public ListarReservas(JFrame owner, boolean modal) {
        super(owner, "Sistema de um Restaurante - Lista de Reservas", modal);
        this.telaInicial = owner;
        initComponents();
        configurarTabela();
        carregarTabela();
    }

    private void configurarTabela() {
        String[] colunas = {"Código da Reserva", "Cliente", "Mesa", "Quantidade de Pessoas", "Observação", "Data da Reserva", "Status"};
        modeloTabela = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblDadosReservas.setModel(modeloTabela);
    }

    private void carregarTabela() {
        try {
            List<Reserva> reservas = rc.listar();
            preencherTabela(reservas);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de banco de dados", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void preencherTabela(List<Reserva> reservas) {
        modeloTabela.setRowCount(0);
        for (Reserva r : reservas) {
            modeloTabela.addRow(new Object[]{r.getCodigo(), r.getNomeCliente(), r.getMesa(), r.getQtdePessoas(), r.getObservacao(), r.getDataReserva(), r.getStatus()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDadosReservas = new javax.swing.JTable();
        btnRemoverReserva = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnCadastrarReserva = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btnAtualizarReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblDadosReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código da Reserva", "Cliente", "Mesa", "Quantidade de Pessoas", "Observação", "Data da Reserva", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblDadosReservas);

        btnRemoverReserva.setText("Remover Reserva");
        btnRemoverReserva.addActionListener(this::btnRemoverReservaActionPerformed);

        btnListar.setText("Listar Todos");
        btnListar.addActionListener(this::btnListarActionPerformed);

        btnCadastrarReserva.setText("Cadastrar Nova Reserva");
        btnCadastrarReserva.addActionListener(this::btnCadastrarReservaActionPerformed);

        btnBuscar.setText("Buscar por Nome de Cliente");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel5.setText("Buscar:");

        btnAtualizarReserva.setText("Atualizar Reserva");
        btnAtualizarReserva.addActionListener(this::btnAtualizarReservaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoverReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnListar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarReserva)
                    .addComponent(btnRemoverReserva)
                    .addComponent(btnAtualizarReserva))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverReservaActionPerformed
        int linha = tblDadosReservas.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma reserva na tabela primeiro.",
                    "Nenhuma reserva selecionada", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int codigo = (int) modeloTabela.getValueAt(linha, 0);
        String nomeCliente = modeloTabela.getValueAt(linha, 1).toString();

        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Remover a reserva de \"" + nomeCliente + "\" (#" + codigo + ")?",
                "Confirmar remoção", JOptionPane.YES_NO_OPTION);
        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            rc.remover(codigo);
            carregarTabela();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de banco de dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverReservaActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        carregarTabela();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnCadastrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarReservaActionPerformed
        dispose();
        CadastrarReserva tela = new CadastrarReserva(telaInicial, true);
        tela.setVisible(true);
    }//GEN-LAST:event_btnCadastrarReservaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String termo = txtBusca.getText().trim();
        try {
            List<Reserva> reservas = rc.buscarPorNome(termo);
            preencherTabela(reservas);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de banco de dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtualizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarReservaActionPerformed
        int linha = tblDadosReservas.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma reserva na tabela primeiro.",
                    "Nenhuma reserva selecionada", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int codigo = (int) modeloTabela.getValueAt(linha, 0);
        String nomeCliente = modeloTabela.getValueAt(linha, 1).toString();
        int mesa = (int) modeloTabela.getValueAt(linha, 2);
        int qtdePessoas = (int) modeloTabela.getValueAt(linha, 3);
        String observacao = modeloTabela.getValueAt(linha, 4).toString();
        String dataReserva = modeloTabela.getValueAt(linha, 5).toString();
        String status = modeloTabela.getValueAt(linha, 6).toString();

        Reserva reservaSelecionada = new Reserva(nomeCliente, mesa, qtdePessoas, observacao, dataReserva, status);
        reservaSelecionada.setCodigo(codigo);

        AtualizarReserva tela = new AtualizarReserva(telaInicial, true, reservaSelecionada);
        tela.setVisible(true);

        carregarTabela();
    }//GEN-LAST:event_btnAtualizarReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ListarReservas dialog = new ListarReservas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarReserva;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrarReserva;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRemoverReserva;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tblDadosReservas;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
