/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controllers.ItemCardapioController;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.ItemCardapio;

/**
 *
 * @author Guilherme Luvison
 */
public class ListarItensCardapio extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListarItensCardapio.class.getName());
    private final ItemCardapioController icc = new ItemCardapioController();
    private DefaultTableModel modeloTabela;
    private final JFrame telaInicial;

    /**
     * Creates new form ListarItensCardapio
     */
    public ListarItensCardapio(JFrame owner, boolean modal) {
        super(owner, "Sistema de um Restaurante - Lista de Itens de Cardápio", modal);
        this.telaInicial = owner;
        initComponents();
        configurarTabela();
        carregarTabela();
    }

    private void configurarTabela() {
        String[] colunas = {"Código", "Nome", "Ingredientes", "Categoria", "Tipo de Prato", "Preço", "Tempo de Preparo"};
        modeloTabela = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblDadosItensCardapio.setModel(modeloTabela);
    }

    private void carregarTabela() {
        try {
            List<ItemCardapio> itensCardapio = icc.listar();
            preencherTabela(itensCardapio);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de banco de dados", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void preencherTabela(List<ItemCardapio> itensCardapio) {
        modeloTabela.setRowCount(0);
        for (ItemCardapio ic : itensCardapio) {
            modeloTabela.addRow(new Object[]{ic.getCodigo(), ic.getNome(), ic.getIngredientes(), ic.getCategoria(), ic.getTipoPrato(), ic.getPreco(), ic.getTempoPreparo()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        btnCadastrarItemCardapio = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDadosItensCardapio = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnAtualizarItemCardapio = new javax.swing.JButton();
        btnRemoverItemCardapio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCadastrarItemCardapio.setText("Cadastrar Novo Item de Cardápio");
        btnCadastrarItemCardapio.addActionListener(this::btnCadastrarItemCardapioActionPerformed);

        btnListar.setText("Listar Todos");
        btnListar.addActionListener(this::btnListarActionPerformed);

        tblDadosItensCardapio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Ingredientes", "Categoria", "Tipo de Prato", "Preço", "Tempo de Preparo"
            }
        ));
        jScrollPane1.setViewportView(tblDadosItensCardapio);

        btnAtualizarItemCardapio.setText("Atualizar Item de Cardápio");
        btnAtualizarItemCardapio.addActionListener(this::btnAtualizarItemCardapioActionPerformed);

        btnRemoverItemCardapio.setText("Remover Item de Cardápio");
        btnRemoverItemCardapio.addActionListener(this::btnRemoverItemCardapioActionPerformed);

        jLabel5.setText("Buscar:");

        btnBuscar.setText("Buscar por Nome");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrarItemCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizarItemCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoverItemCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnListar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarItemCardapio)
                    .addComponent(btnRemoverItemCardapio)
                    .addComponent(btnAtualizarItemCardapio))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarItemCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarItemCardapioActionPerformed
        dispose();
        CadastrarItemCardapio tela = new CadastrarItemCardapio(telaInicial, true);
        tela.setVisible(true);
    }//GEN-LAST:event_btnCadastrarItemCardapioActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        carregarTabela();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAtualizarItemCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarItemCardapioActionPerformed
        int linha = tblDadosItensCardapio.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um item de cardápio na tabela primeiro.",
                    "Nenhum item de cardápio selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int codigo = (int) modeloTabela.getValueAt(linha, 0);
        String nome = modeloTabela.getValueAt(linha, 1).toString();
        String ingredientes = modeloTabela.getValueAt(linha, 2).toString();
        String categoria = modeloTabela.getValueAt(linha, 3).toString();
        String tipoPrato = modeloTabela.getValueAt(linha, 4).toString();
        double preco = (double) modeloTabela.getValueAt(linha, 5);
        String tempoPreparo = modeloTabela.getValueAt(linha, 6).toString();

        ItemCardapio itemCardapioSelecionado = new ItemCardapio(nome, ingredientes, categoria, tipoPrato, preco, tempoPreparo);
        itemCardapioSelecionado.setCodigo(codigo);

        AtualizarItemCardapio tela = new AtualizarItemCardapio(telaInicial, true, itemCardapioSelecionado);
        tela.setVisible(true);

        carregarTabela();
    }//GEN-LAST:event_btnAtualizarItemCardapioActionPerformed

    private void btnRemoverItemCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemCardapioActionPerformed
        int linha = tblDadosItensCardapio.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um item de cardápio na tabela primeiro.",
                    "Nenhum item de cardápio selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int codigo = (int) modeloTabela.getValueAt(linha, 0);
        String nome = modeloTabela.getValueAt(linha, 1).toString();

        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Remover o item de cardápio \"" + nome + "\" (#" + codigo + ")?",
                "Confirmar remoção", JOptionPane.YES_NO_OPTION);
        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            icc.remover(codigo);
            carregarTabela();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de banco de dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverItemCardapioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String termo = txtBusca.getText().trim();
        try {
            List<ItemCardapio> itensCardapio = icc.buscarPorNome(termo);
            preencherTabela(itensCardapio);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de banco de dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ListarItensCardapio dialog = new ListarItensCardapio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarItemCardapio;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrarItemCardapio;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRemoverItemCardapio;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tblDadosItensCardapio;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
